name: custom_locale
description: Storage logic for local custom locale.

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter