name: custom_locale
version: 1.125.0
description: Storage logic for local custom locale.

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  common: any

  flutter:
    sdk: flutter

  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
