name: ergo4all_workspace
description: Workspace package for all ergo4all apps and packages

version: 1.56.2

publish_to: "none" # Remove this line if you wish to publish to pub.dev
workspace:
  - ./packages/common
  - ./packages/common_ui
  - ./packages/custom_locale
  - ./packages/pose
  - ./packages/pose_detect
  - ./packages/pose_analysis
  - ./packages/pose_transforming
  - ./packages/pose_vis
  - ./packages/rula
  - ./packages/user_management
  - ./apps/ergo4all
  - ./apps/pose_tester

environment:
  sdk: ^3.6.0
dependencies:
  glob: ^2.1.3

flutter:
  # We need to include this here, in addition to the actual flutter apps in
  # /apps to get rid of some warnings. Not sure why.
  uses-material-design: true