name: ergo4all_workspace
description: Workspace package for all ergo4all apps and packages

version: 1.51.0

publish_to: "none" # Remove this line if you wish to publish to pub.dev
workspace:
  - ./packages/common
  - ./packages/common_ui
  - ./packages/custom_locale
  - ./packages/pose
  - ./packages/pose_detect
  - ./packages/pose_analysis
  - ./packages/pose_transforming
  - ./packages/pose_vis
  - ./packages/rula
  - ./packages/user_management
  - ./apps/ergo4all
  - ./apps/pose_tester

environment:
  sdk: ^3.6.0
dependencies:
  glob: ^2.1.3
