name: ergo4all_workspace
description: Workspace package for all ergo4all apps and packages

version: 1.30.2

publish_to: "none" # Remove this line if you wish to publish to pub.dev
workspace:
  - ./packages/common
  - ./packages/custom_locale
  - ./packages/pose
  - ./packages/pose_analysis
  - ./packages/rula
  - ./packages/user_management
  - ./packages/pose_tester
  - ./apps/ergo4all

environment:
  sdk: ^3.6.0