name: pose_tester
description: "A small app for testing pose logic on device"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  fast_immutable_collections: ^11.0.0
  fpdart: ^1.1.1
  pose:
    path: "../pose"
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/test_images/
