name: user_management
description: User management logic.

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../common

  equatable: ^2.0.5
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  glados: ^1.1.7
