name: pose_transforming
version: 1.63.0
description: Pose transformation and normalization

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies: 
  common: any
  fast_immutable_collections: ^11.0.3
  pose: any
  pose_analysis: any
  vector_math: ^2.1.4

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^7.0.0
