name: rula
description: Calculation logic for rula scoring

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  fast_immutable_collections: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  glados: ^1.1.7
  parameterized_test: ^2.0.1
