name: rula
description: Calculation logic for rula scoring

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  fast_immutable_collections: ^11.0.0

dev_dependencies:
  glados: ^1.1.7
  parameterized_test: ^2.0.1
  test: ^1.25.8
  very_good_analysis: ^7.0.0
