name: pose_vis
description: Pose visualization logic.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

  pose: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
