name: pose_vis
version: 1.53.0
description: Pose visualization logic.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  common: any

  flutter:
    sdk: flutter

  pose: any
  pose_transforming: any

  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
