name: pose
description: Pose detection files.

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_mlkit_pose_detection: ^0.13.0
  camera: ^0.10.0
  fast_immutable_collections: ^10.2.4
