name: pose
version: 1.123.0
description: Pose detection files.

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  common: any

  fast_immutable_collections: ^11.0.0

  vector_math: ^2.1.4
dev_dependencies:
  very_good_analysis: ^7.0.0
