name: pose
description: Pose detection files.

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  google_mlkit_pose_detection: ^0.13.0
  camera: ^0.10.0
  fast_immutable_collections: ^11.0.0

  common:
    path: ../common

  rula:
    path: ../rula
  vector_math: ^2.1.4
