name: common
version: 1.119.0
description: Common logic which can be used in all project packages.

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  equatable: ^2.0.5
  fast_immutable_collections: ^11.0.0
  fpdart: ^1.1.1
  test: ^1.25.15

dev_dependencies:
  very_good_analysis: ^7.0.0
