name: common_ui
description: Common ui logic for all ergo4all apps.
version: 1.116.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
