name: user_storage
description: Storage logic for local user data.

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../common

  text_storage:
    path: ../text_storage

  equatable: ^2.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  glados: ^1.1.7