name: pose_analysis
description: Pose analysis

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  common: any
  fast_immutable_collections: ^11.0.0
  pose: any
  pose_transforming: any
  rula: any
  vector_math: ^2.1.4

dev_dependencies:
  very_good_analysis: ^7.0.0
