
name: Build

on: 
  push:
    tags: ['v*']

env: 
  JAVA_VERSION: 21

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Flutter ğŸ¦
        uses: kuhnroyal/flutter-fvm-config-action@v2
        with: 
          setup: true
          cache: true

      - name: Cache Flutter dependencies â™»ï¸
        id: cache-flutter
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Very Good CLI ğŸ¦„
        run: dart pub global activate very_good_cli

      - name: Get dependencies ğŸ“¦
        run: very_good packages get -r

      - name: Setup Java â˜•
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{env.JAVA_VERSION}}
          cache: 'gradle'

      - name: Cache build outputs â™»ï¸
        uses: actions/cache@v4
        with:
          path: apps/ergo4all/build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build APKs ğŸ”¨
        run: cd apps/ergo4all ; flutter build apk --release ; cd -

      - name: Build AAB ğŸ”¨
        run: cd apps/ergo4all ; flutter build appbundle --release; cd -

      - name: Upload build â¬†ï¸
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            apps/ergo4all/build/app/outputs/apk/release/app-release.apk
            apps/ergo4all/build/app/outputs/bundle/release/app-release.aab
          retention-days: 2
          
  github-release:
    runs-on: ubuntu-latest
    needs:
        - build-android
    steps:
      - name: Download Android build â¬‡ï¸
        uses: actions/download-artifact@v4
        with:
          name: android-build
          path: build/android
      - name: Make GitHub Release ğŸš€
        uses: softprops/action-gh-release@v2
        with:
          make_latest: 'true'
          files: |
            build/android/**/*-release.*