name: Release

on: 
  workflow_run:
    workflows: [Test]
    types:
      - completed
env: 
  JAVA_VERSION: 17

jobs:
  check-commits:
    name: Check for release
    if: ${{ github.ref == 'refs/heads/main'  && github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    outputs:
      should-release: ${{steps.check-release.outputs.new_release_published}}
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Flutter ğŸ¦
        uses: kuhnroyal/flutter-fvm-config-action@v2
        with: 
          setup: true
          cache: true

      - name: Cache Flutter dependencies â™»ï¸
        id: cache-flutter
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install flutter dependencies ğŸ“¦
        run: flutter pub get --no-example

      - name: Setup node ğŸ’»
        uses: actions/setup-node@v4
        with: 
          node-version-file: .nvmrc

      - name: Check for release ğŸ”
        id: check-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            semantic-release-pub
            @semantic-release/git
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-android:
    name: Build Android
    needs: 
      - check-commits
    if: ${{ needs.check-commits.outputs.should-release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Flutter ğŸ¦
        uses: kuhnroyal/flutter-fvm-config-action@v2
        with: 
          setup: true
          cache: true

      - name: Cache Flutter dependencies â™»ï¸
        id: cache-flutter
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install flutter dependencies ğŸ“¦
        run: flutter pub get --no-example

      - name: Setup Java â˜•
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{env.JAVA_VERSION}}
          cache: 'gradle'

      - name: Cache build outputs â™»ï¸
        uses: actions/cache@v4
        with:
          path: build/
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build APKs ğŸ”¨
        run: flutter build apk --release

      - name: Build AAB ğŸ”¨
        run: flutter build appbundle --release

      - name: Upload build â¬†ï¸
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            build/app/outputs/apk/release/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          retention-days: 2

  semantic-release:
    name: Semantic release
    needs: 
      - build-android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Download Android build â¬‡ï¸
        uses: actions/download-artifact@v4
        with:
          name: android-build
          path: build/android

      - name: Setup Flutter ğŸ¦
        uses: kuhnroyal/flutter-fvm-config-action@v2
        with: 
          setup: true
          cache: true

      - name: Cache Flutter dependencies â™»ï¸
        id: cache-flutter
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup node ğŸ’»
        uses: actions/setup-node@v4
        with: 
          node-version-file: .nvmrc

      - name: Release ğŸš€
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            semantic-release-pub
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
